image: node:14  # Hier Node.js-Image mit gewünschter Version

stages:
  - frontend_build
  - backend_build
  - frontend_test
  - backend_test

variables:
  # Definiere hier eventuelle Umgebungsvariablen, die in den Jobs verwendet werden sollen

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - apt-get install -y openjdk-11-jdk  # JDK-Installation für alle Jobs

frontend_build:
  stage: frontend_build
  script:
    - cd angular-frontend
    - npm install
    - npx ng build --configuration=production

  only:
    - dev

backend_build:
  stage: backend_build
  script:
    - cd spring-boot-backend
    - ./mvnw clean install
  only:
    - dev

frontend_test:
  stage: frontend_test
  script:
    - cd angular-frontend
    - npm install
    - npx ng test
  only:
    - dev

backend_test:
  stage: backend_test
  script:
    - cd spring-boot-backend
    - ./mvnw test
  only:
    - dev
